In [2]:
import pandas as pd
import numpy as np
pdf=pd.read_excel("C:\\Users\\chandini ch\\Downloads\\EXL Shared Partner Data.xlsx")

In [3]:
pdf.shape

(458872, 15)

In [4]:
pdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 458872 entries, 0 to 458871
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Application_Nr       458862 non-null  str
 1   QuoteGeneratedDate   458872 non-null  datetime64[us]
 2   OfferCoverageAmount  458872 non-null  int64
 3   Offer_Stat_Desc      458872 non-null  str
 4   OfferPremiumAmount   458872 non-null  float64
 5   OfferBillingMethod   458872 non-null  str
 6   Pmnt_Freq_Desc       458832 non-null  str
 7   Effective_Date       190605 non-null  datetime64[us]
 8   Paid_To_Date         190605 non-null  datetime64[us]
 9   Offered_NAP          458872 non-null  float64
 10  Issued_NAP           190605 non-null  float64
 11  CurrentBillMethod    190605 non-null  str
 12  ProductType          458862 non-null  str
 13  Age_at_AppReceived   400627 non-null  float64
 14  PartnerMarker        458872 non-null  str
dtypes: datetime64[us](3), float64(4), int64(1), str(7)
memory usage: 52.5 MB

In [5]:
pdf.dropna(subset="Application_Nr",inplace=True)
pdf.isna().sum()

Application_Nr              0
QuoteGeneratedDate          0
OfferCoverageAmount         0
Offer_Stat_Desc             0
OfferPremiumAmount          0
OfferBillingMethod          0
Pmnt_Freq_Desc             40
Effective_Date         268257
Paid_To_Date           268257
Offered_NAP                 0
Issued_NAP             268257
CurrentBillMethod      268257
ProductType                10
Age_at_AppReceived      58235
PartnerMarker               0
dtype: int64

In [6]:
pdf["Pmnt_Freq_Desc"]=pdf["Pmnt_Freq_Desc"].fillna("Monthly")

In [7]:
pdf.isna().sum()

Application_Nr              0
QuoteGeneratedDate          0
OfferCoverageAmount         0
Offer_Stat_Desc             0
OfferPremiumAmount          0
OfferBillingMethod          0
Pmnt_Freq_Desc              0
Effective_Date         268257
Paid_To_Date           268257
Offered_NAP                 0
Issued_NAP             268257
CurrentBillMethod      268257
ProductType                10
Age_at_AppReceived      58235
PartnerMarker               0
dtype: int64

In [8]:
pdf["Effective_Date"]=pd.to_datetime(pdf["Effective_Date"])
pdf["Effective_Date"]=pdf["Effective_Date"].interpolate()
pdf.isna().sum()

Application_Nr              0
QuoteGeneratedDate          0
OfferCoverageAmount         0
Offer_Stat_Desc             0
OfferPremiumAmount          0
OfferBillingMethod          0
Pmnt_Freq_Desc              0
Effective_Date              1
Paid_To_Date           268257
Offered_NAP                 0
Issued_NAP             268257
CurrentBillMethod      268257
ProductType                10
Age_at_AppReceived      58235
PartnerMarker               0
dtype: int64

In [9]:
pdf.dropna(subset="Effective_Date",inplace=True)

In [10]:
pdf["Paid_To_Date"]=pd.to_datetime(pdf["Paid_To_Date"])
pdf["Paid_To_Date"]=pdf["Paid_To_Date"].interpolate()
pdf.dropna(subset="Paid_To_Date",inplace=True)

In [11]:
pdf["Issued_NAP"]=pdf["Issued_NAP"].fillna(pdf["Offered_NAP"])

In [12]:
pdf["CurrentBillMethod"]=pdf["CurrentBillMethod"].ffill()

In [13]:
pdf["ProductType"]=pdf["ProductType"].fillna("SI Whole Life")

In [14]:
pdf["Age_at_AppReceived"]=pdf["Age_at_AppReceived"].fillna(pdf["Age_at_AppReceived"].mean())

In [15]:
from datetime import datetime
pdf["Quote_Generate_month"] = pdf["QuoteGeneratedDate"].apply(lambda x: datetime.strftime(x, '%y-%m'))
pdf["Quote_Generate_year"] = pdf["QuoteGeneratedDate"].apply(lambda x: datetime.strftime(x, '%y'))

In [16]:
pdf["Effective_Date_month"] = pdf["Effective_Date"].apply(lambda x: datetime.strftime(x, '%y-%m'))
pdf["Effective_Date_year"] = pdf["Effective_Date"].apply(lambda x: datetime.strftime(x, '%y'))

In [17]:
pdf['Paid_To_Date_month'] = pdf['Paid_To_Date'].apply(lambda x: datetime.strftime(x, '%y-%m'))
pdf['Paid_To_Date_year'] = pdf['Paid_To_Date'].apply(lambda x: datetime.strftime(x, '%y'))
pdf.isna().sum()

Application_Nr          0
QuoteGeneratedDate      0
OfferCoverageAmount     0
Offer_Stat_Desc         0
OfferPremiumAmount      0
OfferBillingMethod      0
Pmnt_Freq_Desc          0
Effective_Date          0
Paid_To_Date            0
Offered_NAP             0
Issued_NAP              0
CurrentBillMethod       0
ProductType             0
Age_at_AppReceived      0
PartnerMarker           0
Quote_Generate_month    0
Quote_Generate_year     0
Effective_Date_month    0
Effective_Date_year     0
Paid_To_Date_month      0
Paid_To_Date_year       0
dtype: int64

In [18]:
pdf=pdf[['Quote_Generate_year','OfferCoverageAmount','Offer_Stat_Desc','OfferPremiumAmount','OfferBillingMethod','Pmnt_Freq_Desc','Effective_Date_year','Paid_To_Date_year','Offered_NAP','Issued_NAP','CurrentBillMethod','ProductType','Age_at_AppReceived','PartnerMarker']]
pdf.tail(5)

,Quote_Generate_year,OfferCoverageAmount,Offer_Stat_Desc,OfferPremiumAmount,OfferBillingMethod,Pmnt_Freq_Desc,Effective_Date_year,Paid_To_Date_year,Offered_NAP,Issued_NAP,CurrentBillMethod,ProductType,Age_at_AppReceived,PartnerMarker
458867,22,70000,Carrier declined to issue,186.6,ACH/PAC,Monthly,22,22,2239.2,2239.2,CRD,SI Term Band 1,61.000000,Ethos
458868,22,300000,Lapsed Abandoned,68.0,ACH/PAC,Monthly,22,22,816.0,816.0,CRD,SI Term Band 2,55.467084,Ethos
458869,22,250000,Lapsed Abandoned,55.0,ACH/PAC,Monthly,22,22,660.0,660.0,CRD,SI Term Band 2,33.000000,Liberty
458870,22,80000,Lapsed Abandoned,89.4,ACH/PAC,Monthly,22,22,1072.8,1072.8,CRD,TAWL,32.000000,Liberty
458871,22,30000,Lapsed Abandoned,294.3,ACH/PAC,Monthly,22,22,3531.6,3531.6,CRD,TAWL,55.467084,Liberty

In [19]:
pdf.isna().sum()

Quote_Generate_year    0
OfferCoverageAmount    0
Offer_Stat_Desc        0
OfferPremiumAmount     0
OfferBillingMethod     0
Pmnt_Freq_Desc         0
Effective_Date_year    0
Paid_To_Date_year      0
Offered_NAP            0
Issued_NAP             0
CurrentBillMethod      0
ProductType            0
Age_at_AppReceived     0
PartnerMarker          0
dtype: int64

In [20]:
pdf.info()
pdf.shape

<class 'pandas.DataFrame'>
Index: 458861 entries, 1 to 458871
Data columns (total 14 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Quote_Generate_year  458861 non-null  str
 1   OfferCoverageAmount  458861 non-null  int64
 2   Offer_Stat_Desc      458861 non-null  str
 3   OfferPremiumAmount   458861 non-null  float64
 4   OfferBillingMethod   458861 non-null  str
 5   Pmnt_Freq_Desc       458861 non-null  str
 6   Effective_Date_year  458861 non-null  str
 7   Paid_To_Date_year    458861 non-null  str
 8   Offered_NAP          458861 non-null  float64
 9   Issued_NAP           458861 non-null  float64
 10  CurrentBillMethod    458861 non-null  str
 11  ProductType          458861 non-null  str
 12  Age_at_AppReceived   458861 non-null  float64
 13  PartnerMarker        458861 non-null  str
dtypes: float64(4), int64(1), str(9)
memory usage: 52.5 MB

(458861, 14)

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
pdf['Quote_Generate_year'] = le.fit_transform(pdf['Quote_Generate_year'])
print(pdf['Quote_Generate_year'])

1         0
2         0
3         0
4         0
5         0
         ..
458867    4
458868    4
458869    4
458870    4
458871    4
Name: Quote_Generate_year, Length: 458861, dtype: int64

In [22]:
pdf.head(3)

,Quote_Generate_year,OfferCoverageAmount,Offer_Stat_Desc,OfferPremiumAmount,OfferBillingMethod,Pmnt_Freq_Desc,Effective_Date_year,Paid_To_Date_year,Offered_NAP,Issued_NAP,CurrentBillMethod,ProductType,Age_at_AppReceived,PartnerMarker
1,0,10000,Signed,74.80,Credit Card,Monthly,18,22,897.6,897.6,PAC,SI Whole Life,70.0,Liberty
2,0,15000,Signed,42.35,Credit Card,Monthly,18,22,508.2,508.2,DIR,SI Whole Life,54.0,Liberty
3,0,15000,Signed,57.05,Credit Card,Monthly,18,22,684.6,684.6,DIR,SI Whole Life,58.0,Liberty

In [23]:
pdf['Offer_Stat_Desc'] = le.fit_transform(pdf['Offer_Stat_Desc'])
pdf['OfferBillingMethod'] = le.fit_transform(pdf['OfferBillingMethod'])
pdf['Pmnt_Freq_Desc'] = le.fit_transform(pdf['Pmnt_Freq_Desc'])
pdf['CurrentBillMethod'] = le.fit_transform(pdf['CurrentBillMethod'])
pdf['ProductType'] = le.fit_transform(pdf['ProductType'])
pdf['PartnerMarker'] = le.fit_transform(pdf['PartnerMarker'])

In [24]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
pdf = sc.fit_transform(pdf)

In [25]:
pdf = pd.DataFrame(pdf)
pdf.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,-3.213333,-0.517027,0.989585,-0.009588,1.541918,-0.036573,-3.244363,0.675639,0.008324,0.008058,1.392357,0.490995,1.175122,-0.457468
1,-3.213333,-0.435513,0.989585,-0.485168,1.541918,-0.036573,-3.244363,0.675639,-0.540301,-0.540905,-0.160232,0.490995,-0.118627,-0.457468
2,-3.213333,-0.435513,0.989585,-0.269728,1.541918,-0.036573,-3.244363,0.675639,-0.291771,-0.292222,-0.160232,0.490995,0.204810,-0.457468

In [26]:
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
x=pdf
wcss=[]
silhouette = []
for i in range(2,11):
    km1=KMeans(n_clusters=3,random_state=50)
    labels=km1.fit_predict(x)
    wcss.append(km1.inertia_)
    silhouette.append(silhouette_score(x,labels))
print(silhouette)

[0.175064809037187, 0.175064809037187, 0.175064809037187, 0.175064809037187, 0.175064809037187, 0.175064809037187, 0.175064809037187, 0.175064809037187, 0.175064809037187]